# Gole- to deploy build images form CI step once the CI workflow is succeded
name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Copy .env file to main env file
        run: cp .env.example .env
      - name: Login as Docker
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Deploy the container with docker-compose
        run: |
          docker compose pull
          docker compose up -d
